### ISSUE TITLE
When Will 1.0.0 comes?

### ISSUE THREAD

**Issue by eacdy** [resilience4j/resilience4j#604] opened 2019-09-04 08:12 UTC
When Will 1.0.0 comes?

I really like these features:
* <https://github.com/resilience4j/resilience4j/pull/566>
* <https://github.com/resilience4j/resilience4j/issues/546>
HOPE 1.0.0 RELEASE soon!

**Comment by RobWin** [comment] 2019-09-04 09:09
duplicate of #429

**Closed by RobWin** 2019-09-04 09:09 UTC
