### ISSUE TITLE
Circuit breaker: evaluate response as a failure

### ISSUE THREAD

**Issue by jabrena** [resilience4j/resilience4j#589] opened 2019-08-25 18:48 UTC
Hi,

I was checking the options for Circuit Breaker:
https://resilience4j.readme.io/docs/circuitbreaker

But I didn´t see the possibility to evaluate a successful response as a failure. This possibility is available for another behaviour Retry:
https://resilience4j.readme.io/docs/retry

```
retryOnResultPredicate
result -> false
Configures a Predicate which evaluates if a result should be retried. The Predicate must return true, if the result should be retried, otherwise it must return false.
```

Do you think that it is possible to add something similar in this behaviour?

Many thanks in advance.

Juan Antonio

**Comment by harishmbm** [comment] 2019-08-26 01:06
The simplest way is to throw an exception from your client (for the successful response you want to mark as failure) and put that exception in record exception list of circuit breaker.

**Comment by RobWin** [comment] 2019-08-26 06:14
Hi, 
no, not yet.
I close this issue, because it's a duplicate of https://github.com/resilience4j/resilience4j/issues/384
Please have a look at the discussion.

**Closed by RobWin** 2019-08-26 06:14 UTC

**Comment by RobWin** [comment] 2019-08-26 06:19
We created a [SupplierUtils](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-core/src/main/java/io/github/resilience4j/core/SupplierUtils.java) which helps you in situations where you can't modify the client code.

```
Supplier<HttpResponse> supplier = () -> httpClient.doRemoteCall();
Supplier<String> supplierWithResultHandling = SupplierUtils.andThen(supplier, result -> {
    if (result.getStatusCode() == 400) {
       throw new HttpClientServerException();
    } else if (result.getStatusCode() == 500) {
       throw new HttpServerException();
    }
    return result;
});
HttpResponse httpResponse = circuitBreaker
  .executeSupplier(supplierWithResultHandling);
````

**Comment by jabrena** [comment] 2019-08-26 06:40
Many thanks, I will try this approach

**Comment by jabrena** [comment] 2019-08-31 10:00
Applied the solution and the usage is easy.
