### ISSUE TITLE
Should not use same metric name with two different types of metrics

### ISSUE THREAD

**Issue by jkschneider** [resilience4j/resilience4j#988] opened 2020-05-07 18:12 UTC
In circuit breaker metrics, we have the same metric name being applied to timers with two different tags (OK) but also a counter with similar tags (not ok).

For some monitoring systems (e.g. Stackdriver), the structure of the metric that needs to be sent will be established by name alone, such that there can't exist two metrics of the same name but different types.

[Here](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-micrometer/src/main/java/io/github/resilience4j/micrometer/tagged/AbstractCircuitBreakerMetrics.java#L119-L138) is the offending block.

**Comment by RobWin** [comment] 2020-05-08 06:26
Thank you.
Duplicate of #942

**Closed by RobWin** 2020-05-08 06:26 UTC
