### ISSUE TITLE
No Maven BOM for version 1.7.1 in Maven central

### ISSUE THREAD

**Issue by cmacq2** [resilience4j/resilience4j#1733] opened 2022-07-25 08:14 UTC
Resilience4j version: 1.7.1

While working on the scaffolding of a project using resilience4j, I noticed that there is a BOM for 1.7.0, but not for 1.7.1 in Maven central despite individual components being available at 1.7.1 (e.g. core, retry, bulkhead).

**Comment by RobWin** [comment] 2022-09-21 07:09
Duplicate of https://github.com/resilience4j/resilience4j/issues/1558

**Closed by RobWin** 2022-09-21 07:09 UTC
