### ISSUE TITLE
resilience4j-bom not available in maven central

### ISSUE THREAD

**Issue by elue** [resilience4j/resilience4j#1814] opened 2022-11-18 11:55 UTC
Resilience4j version: 1.7.1

Is there any reason that the 1.7.1 RELEASE does not have  a bom?

``` 
            <dependency>
                <groupId>io.github.resilience4j</groupId>
                <artifactId>resilience4j-bom</artifactId>
                <version>1.7.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

1.7.0 one is there, so would expect 1.7.1 as well.

**Comment by RobWin** [comment] 2022-11-18 12:12
Duplicate of  https://github.com/resilience4j/resilience4j/issues/1472

**Closed by RobWin** 2022-11-18 12:12 UTC
