### ISSUE TITLE
status:Unknown with /actuator/helath

### ISSUE THREAD

**Issue by upen4a3** [resilience4j/resilience4j#1074] opened 2020-07-14 00:03 UTC
Resilience4j version:1.5.0

Java version:11

I am getting 

```
"circuitBreakers": {
            "status": "UNKNOWN"
        },
```

![image](https://user-images.githubusercontent.com/15043841/87365235-4f283980-c53b-11ea-8b0c-8ce354bad9b4.png)

Do I need to do any extra configurations?

my application.properties looks below all other metrics works fine.

```

spring.application.name=resilience4j-demo
spring.jackson.serialization.indent_output=true

server.port=8080

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.health.diskspace.enabled=false
management.health.circuitbreakers.enabled=true
management.health.ratelimiters.enabled=false

info.name=${spring.application.name}
info.description = resilience4j demo
info.environment=${spring.profiles.active}
info.version= 0.0.1


management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles-histogram.resilience4j.circuitbreaker.calls=true

#resilience4j.circuitbreaker.metrics.use_legacy_binder: true

resilience4j.circuitbreaker.configs.default.register-health-indicator=false
resilience4j.circuitbreaker.configs.default.sliding-window-size=10
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls=5
resilience4j.circuitbreaker.configs.default.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.configs.default.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=20
resilience4j.circuitbreaker.configs.default.event-consumer-buffer-size=10
resilience4j.circuitbreaker.configs.default.record-exceptions=org.springframework.web.client.HttpServerErrorException

resilience4j.circuitbreaker.instances.backendService.base-config=default

```

**Comment by RobWin** [comment] 2020-07-14 11:56
Which Spring Boot version do you use?

**Comment by upendar4a3** [comment] 2020-07-14 13:45
Spring boot 2.30 RELEASE

**Comment by RobWin** [comment] 2020-07-15 07:46
Could you please debug into this line and show some screenshots?

https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring-boot2/src/main/java/io/github/resilience4j/circuitbreaker/monitoring/health/CircuitBreakersHealthIndicator.java#L93

**Comment by upendar4a3** [comment] 2020-07-15 15:14
Unfortunately when i call /actuator/health,The particular class you mentioned is not being called at ,the call is being returned from 

org.springframework.boot.actuate.health.HealthEndpointSupport<C, T>

![image](https://user-images.githubusercontent.com/15043841/87562691-e8626780-c683-11ea-9bd6-30f1258c4b39.png)

**Comment by RobWin** [comment] 2020-07-16 07:32
But you are using our Spring Boot 2 starter?

**Comment by upendar4a3** [comment] 2020-07-16 16:40
This is my POM looks like

```

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.3.0.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>11</java.version>
		<git-commit-id-plugin.version>2.2.4</git-commit-id-plugin.version>
		<resilence4j.plugin.version>1.4.0</resilence4j.plugin.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-spring-boot2</artifactId>
			<version>${resilence4j.plugin.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aop</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
	</dependencies>

	<build>
		<plugins>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
		</repository>
		<repository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
		</pluginRepository>
		<pluginRepository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>

</project>

```

**Comment by soham9** [comment] 2020-11-11 12:36
Even I'm facing the same issue

**Comment by RobWin** [comment] 2020-11-11 15:42
Did you set
`resilience4j.circuitbreaker.configs.default.register-health-indicator=true`

**Comment by gwimmel** [comment] 2020-11-24 20:01
I have a similar / maybe the same problem (I use resilience4j 1.6.1, Spring Boot 2.2.4). I set
`resilience4j.circuitbreaker.configs.default.register-health-indicator=false`
(as in the example above), as I explicitly do not want to have circuitbreaker health indicators.

But then I get a health item `"circuitBreakers":{"status":"UNKNOWN"}`  on the health endpoint (which has an effect on the overall health status of my application). Is this the intended behavior? Is there a way to disable the circuitBreakers health check completely, so that there is no circuitBreakers health item?

When I set `resilience4j.circuitbreaker.configs.default.register-health-indicator=true` I get a circuitBreakers health item with detail data of the circuit breaker, but that's not what I want.

**Comment by RobWin** [comment] 2020-12-17 07:12
Would someone like to contribute a bugfix?

**Comment by gwimmel** [comment] 2021-01-09 14:20
I could take a closer look now and found out that I overlooked that the CircuitBreaker health indicator can be disabled completely via the configuration `management.health.circuitbreakers.enabled=false` (or by not setting `management.health.circuitbreakers.enabled` at all). That's sufficient for my use case.

That there is a CircuitBreaker health indicator with UNKNOWN status if  `management.health.circuitbreakers.enabled=true` is set and all circuit breakers are configured with `...register-health-indicator=false` is because the default Spring status aggregator used in [CircuitBreakersHealthIndicator.java](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring-boot2/src/main/java/io/github/resilience4j/circuitbreaker/monitoring/health/CircuitBreakersHealthIndicator.java#L110) computes an aggregate status UNKNOWN if the passed set of statuses is empty.

One could easily change the implementation of `CircuitBreakersHealthIndicator.java` such that in this case it returns an UP status immediately without calling the status aggregator, but that seems a bit unnatural to me. Maybe it's even a good thing to have an UNKNOWN status in this case, to be reminded that you've enabled the CircuitBreakers health indicator but did not register any health indicators for the specific circuit breakers. If one really wants to have this behaviour, one could manually configure a `CircuitBreakersHealthIndicator` bean in one's application with an appropriate status aggregator.

What do you think?

**Comment by Romeh** [comment] 2021-01-22 11:17
for me it make sense what @gwimmel  just explained , @RobWin  what do u think ?

**Comment by RobWin** [comment] 2021-01-22 11:21
Yes, I think we won't change the implementation because of backwards compatibility.

**Comment by Romeh** [comment] 2021-02-18 10:32
ok closing the ticket as nothing more is required from our side , feel free to open new if you have new questions

**Closed by Romeh** 2021-02-18 10:32 UTC
Labels: question

**Comment by Js109** [comment] 2022-01-17 16:19
resilience4j.circuitbreaker.instances.orderService.registerHealthIndicator=true

in combination with:
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

solved the problem for me.


Beside that I was using:
# resilience4j circuitBreaker config
resilience4j.circuitbreaker.instances.orderService.failure-rate-threshold=80
resilience4j.circuitbreaker.instances.orderService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.orderService.sliding-window-size=5
resilience4j.circuitbreaker.instances.orderService.permitted-number-of-calls-in-half-open-state=1
resilience4j.circuitbreaker.instances.orderService.wait-duration-in-open-state=60000
resilience4j.circuitbreaker.instances.orderService.ignore-exceptions=org.springframework.web.client.HttpClientErrorException
resilience4j.circuitbreaker.instances.orderService.automatic-transition-from-open-to-half-open-enabled=true

**Comment by ousiax** [comment] 2024-01-02 15:00
```xml
    ...
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.2.1</version>
		<relativePath />
		<!-- lookup parent from repository -->
	</parent>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-circuitbreaker-resilience4j</artifactId>
		</dependency>
		...
```
For me, it seems that the circuit breaker should be triggered to update the status. That is, we need to make a request that wrapped by the circuit breaker first.
