### ISSUE TITLE
UndeclaredThrowableException Caused by IllegalAccessException with fallbackMethod

### ISSUE THREAD

**Issue by earlbread** [resilience4j/resilience4j#1770] opened 2022-09-28 03:47 UTC
Resilience4j version: 1.7.1

Java version: 1.8

I've found that the following exception occurs intermittently:

```
java.lang.reflect.UndeclaredThrowableException: null
...
Caused by: java.lang.IllegalAccessException: Class io.github.resilience4j.fallback.FallbackMethod can not access a member of class com.my.class with modifiers "private"
```

I checked issue #878, and it seems to happen even though my library version is 1.7.1.
Is there any other solution other than changing the fallback method to public?

**Comment by RobWin** [comment] 2022-09-28 06:54
Hi,
did it work in the past for you?
Did you check your transitive dependencies. Sometimes people are using Spring Cloud CircuitBreaker which used an older version.

**Comment by earlbread** [comment] 2022-09-29 01:14
Hi, thanks for your answer.
I didn't used CircuitBreaker before for this code. This is the first time.
I think I'm not using Spring Cloud CircuitBreaker.

```
import io.github.resilience4j.circuitbreaker.annotation.CircuitBreaker;
```

```
Caused by: java.lang.IllegalAccessException: Class io.github.resilience4j.fallback.FallbackMethod can not access a member of class com.my.class with modifiers "private"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102) ~[na:1.8.0_292]
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296) ~[na:1.8.0_292]
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288) ~[na:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:491) ~[na:1.8.0_292]
	at io.github.resilience4j.fallback.FallbackMethod.invoke(FallbackMethod.java:212) ~[resilience4j-spring-1.7.1.jar!/:1.7.1]
	at io.github.resilience4j.fallback.FallbackMethod.fallback(FallbackMethod.java:160) ~[resilience4j-spring-1.7.1.jar!/:1.7.1]
	at io.github.resilience4j.fallback.DefaultFallbackDecorator.lambda$decorate$52452fd9$1(DefaultFallbackDecorator.java:40) ~[resilience4j-spring-1.7.1.jar!/:1.7.1]
	at io.github.resilience4j.circuitbreaker.configure.CircuitBreakerAspect.circuitBreakerAroundAdvice(CircuitBreakerAspect.java:118) ~[resilience4j-spring-1.7.1.jar!/:1.7.1]
	at sun.reflect.GeneratedMethodAccessor1923.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_292]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629) ~[spring-aop-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618) ~[spring-aop-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) ~[spring-aop-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673) ~[spring-aop-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	... 9 common frames omitted
```

**Comment by RobWin** [comment] 2022-09-29 05:29
Can you please check your transitive dependencies. Which Spring Cloud Version are you using?

**Comment by earlbread** [comment] 2022-09-29 05:39
I'm using spring cloud 1.3.5.
I'll attach a list of dependencies. Please let me know if you need any other information.

```
./gradlew dependencies my-app:dependencies | grep "resilience\|spring-cloud" > dependencies.txt
```
[dependencies.txt](https://github.com/resilience4j/resilience4j/files/9671334/dependencies.txt)

**Comment by RobWin** [comment] 2022-09-29 06:18
Looks good to me.
Then it must also be some sort of race condition as suggested in the issue #878

**Comment by earlbread** [comment] 2022-09-29 06:27
If so, the only solution is to make the method public?

**Comment by RobWin** [comment] 2022-09-29 06:29
Yes, and/or contribute a bug fix :D

**Comment by RobWin** [comment] 2022-09-29 06:30
I close this as a duplicate of #878

**Closed by RobWin** 2022-09-29 06:30 UTC
Labels: question

**Comment by earlbread** [comment] 2022-09-29 06:47
Thanks!
