### ISSUE TITLE
resilience4j-spring-boot2 1.3.1 references an old version of resilience4j-circuitbreaker 

### ISSUE THREAD

**Issue by yoep** [resilience4j/resilience4j#864] opened 2020-02-12 08:32 UTC
Resilience4j version: 1.3.1

Java version: 11

The `resilience4j-spring-boot2` dependency still references to the old version of `resilience4j-circuitbreaker` 1.1.0 causing conflicts on `resilience4j-core` when trying to use another module (such as timelimiter).
This breaks the circuit breaker or timelimiter modules as the `resilience4j-core` version 1.1.0 & 1.3.1 breaks one of the modules.

### Dependency tree

```
+-io.github.resilience4j:resilience4j-spring-boot2:1.3.1
    +-io.github.resilience4j:resilience4j-spring-boot-common:1.3.1
      +-io.github.resilience4j:resilience4j-spring:1.3.1
        +-io.github.resilience4j:resilience4j-framework-common:1.3.1
          +-io.github.resilience4j:resilience4j-core:1.3.1
and
+-io.github.resilience4j:resilience4j-spring-boot2:1.3.1
    +-io.github.resilience4j:resilience4j-spring-boot-common:1.3.1
      +-io.github.resilience4j:resilience4j-spring:1.3.1
        +-io.github.resilience4j:resilience4j-framework-common:1.3.1
          +-io.github.resilience4j:resilience4j-circuitbreaker:1.1.0
            +-io.github.resilience4j:resilience4j-core:1.1.0
```

### Known workaround
Force `resilience4j-circuitbreaker` to version 1.3.1 with dependency management.

**Comment by RobWin** [comment] 2020-02-12 08:59
Duplicate of #859 and #848

**Comment by RobWin** [comment] 2020-02-12 09:00
Please have a look at the issues.
I guess you use a spring cloud dependency bomb which has old versions. You need to exclude or override them.

**Closed by RobWin** 2020-02-12 09:00 UTC
