### ISSUE TITLE
Suport new Spring Boot 3 autoconfiguration imports file

### ISSUE THREAD

**Issue by spencergibb** [resilience4j/resilience4j#1766] opened 2022-09-22 20:56 UTC
Spring Boot 2.7 added a new mechanism to specify auto-configuration. See https://github.com/spring-projects/spring-boot/issues/29698

Spring Boot 3 removed the ability to load auto-configuration via spring.factories https://github.com/spring-projects/spring-boot/issues/29699

https://github.com/spring-cloud/spring-cloud-circuitbreaker will add these temporarily until support is added here.

/cc @ryanjbaxter

**Comment by magnus-larsson** [comment] 2022-11-25 09:50
Is this issue fixed in Resilience4J 2.0.0?

I tried using Spring Boot 3.0.0 with Resilience4J 2.0.0 in the project git@github.com:resilience4j/resilience4j-spring-boot2-demo.git.

I simply upgraded Spring Boot to 3.0.0 in the file `build.gradle.kts` and then run the command: `./gradlew clean build`

It resulted in all tests failing on missing bean exceptions.

After adding a file described above, e.g. https://github.com/spring-cloud/spring-cloud-circuitbreaker/blob/main/spring-cloud-circuitbreaker-resilience4j/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, all tests, and the build run ok.

**Comment by RobWin** [comment] 2022-11-25 10:16
https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring-boot2/src/main/resources/META-INF/org.springframework.boot.autoconfigure.AutoConfiguration.imports

**Comment by RobWin** [comment] 2022-11-25 10:17
aah
I missed this detail :(
It must be part of the `spring` folder.
Damn.

**Comment by magnus-larsson** [comment] 2022-11-25 11:48
Yes, it has to.

**Comment by RobWin** [comment] 2022-11-28 10:44
I added a `resilience4j-spring-boot3` module.
You can try `2.0.1-SNAPSHOT` if it works for you.
I also created a new repo `resilience4j-spring-boot3-demo`.

**Comment by magnus-larsson** [comment] 2022-11-29 10:24
Great, thanks!

I tried out the new resilience4j-spring-boot3 v2.0.1-SNAPSHOT - module, and it worked fine!

I'll try out the resilience4j-spring-boot3-demo - project as soon as I can find some time. I'll report issues, if any :-)

**Comment by RobWin** [comment] 2022-11-29 13:08
The module `resilience4j-spring-boot3` will have a new package structure.
@spencergibb Is this important for you in Spring Cloud Circuitbreaker?

**Comment by ryanjbaxter** [comment] 2022-11-29 14:28
@RobWin what should we be using instead of Vavr?  I see the dependency was removed, but the documentation samples still show it being used.

**Comment by RobWin** [comment] 2022-11-29 14:33
Do you have a concrete example where you are using Vavr?
We still have `resilience4j-vavr` to support the decoration of Either, Try, CheckedFunction, ...

**Comment by ryanjbaxter** [comment] 2022-11-29 14:38
Similar to this example from the docs

// Given
CircuitBreaker circuitBreaker = CircuitBreaker.ofDefaults("testName");

// When I decorate my function
CheckedFunction0<String> decoratedSupplier = CircuitBreaker
        .decorateCheckedSupplier(circuitBreaker, () -> "This can be any method which returns: 'Hello");

// and chain an other function with map
Try<String> result = Try.of(decoratedSupplier)
                .map(value -> value + " world'");

// Then the Try Monad returns a Success<String>, if all functions ran successfully.
assertThat(result.isSuccess()).isTrue();
assertThat(result.get()).isEqualTo("This can be any method which returns: 'Hello world'");

**Comment by RobWin** [comment] 2022-11-29 14:51
Yes thanks. I need to fix the docs. 
Here we have a non-backwards compatible change, because of the removal of Vavr.

Together with Vavr, it would look like this now.

CheckedSupplier is not backwards-compatible:

```
       // When I decorate my function
        CheckedSupplier<String> decoratedSupplier = CircuitBreaker
            .decorateCheckedSupplier(circuitBreaker, () -> "This can be any method which returns: 'Hello");

        // and chain an other function with map
        Try<String> result = Try.of(decoratedSupplier::get)
            .map(value -> value + " world'");
```

Supplier is backwards-compatible:

```` 
        Supplier<String> decoratedSupplier = CircuitBreaker
            .decorateSupplier(circuitBreaker, () -> "This can be any method which returns: 'Hello");

        // and chain an other function with map
        Try<String> result = Try.ofSupplier(decoratedSupplier)
            .map(value -> value + " world'");
```

**Comment by RobWin** [comment] 2022-11-29 15:11
Yes, if you still want to make use of Vavr features. 
Is Vavr part of the API of the Spring Boot Cloud CircuitBreaker?

**Comment by ryanjbaxter** [comment] 2022-11-29 15:14
No we were just using it because it was inherited through Resilience4J

**Comment by RobWin** [comment] 2022-11-29 15:17
You mean here, or?
https://github.com/spring-cloud/spring-cloud-circuitbreaker/blob/main/spring-cloud-circuitbreaker-resilience4j/src/main/java/org/springframework/cloud/circuitbreaker/resilience4j/Resilience4JCircuitBreaker.java#L108

**Comment by RobWin** [comment] 2022-11-29 15:18
I think I would drop Vavr in Cloud Circuitbreaker 3.x and replace it by a try/catch.

**Comment by ryanjbaxter** [comment] 2022-11-29 15:38
OK thats simple enough.

FYI we won't be able to upgrade to 2.0.0 because of this
https://github.com/resilience4j/resilience4j/issues/1825

Can you point me to the snapshots repo so I can try 2.0.1?

**Comment by RobWin** [comment] 2022-11-29 15:42
Yes, I plan to release 2.0.1 as soon as the next PR is merged. 
The PR provides a new feature to modify even shareable circuitbreaker configs with Customizer Beans.

Repo is: https://oss.sonatype.org/content/repositories/snapshots

**Comment by ryanjbaxter** [comment] 2022-11-29 15:48
OK I can confirm 2.0.1-SNAPSHOT works.  We plan on doing our GA release of Spring Cloud CircuitBreaker based on Spring Boot 3.0.0 on December 14th.  It would be great is we could have the next Resilience4J release included in that.

**Comment by RobWin** [comment] 2022-11-29 15:50
Should be possible

**Comment by ryanjbaxter** [comment] 2022-11-29 15:52
Awesome!  Thanks for the help!  Just tag me when the new release is available.

**Comment by ryanjbaxter** [comment] 2022-11-29 15:55
FYI might want to update docs here on snapshots https://resilience4j.readme.io/docs/gradle

**Closed** 2022-12-05 14:37 UTC
Labels: enhancement

**Comment by ryanjbaxter** [comment] 2022-12-05 22:14
Thanks!  I just pushed the changes to Spring Cloud CircuitBreaker!

**Comment by RobWin** [comment] 2022-12-09 08:37
@ryanjbaxter I have to release a 2.0.2 version, because of a bug :/

**Comment by ryanjbaxter** [comment] 2022-12-09 15:19
Thanks, I have upgraded
