### ISSUE TITLE
New closeCurrentPeriod method in rate limiter

### ISSUE THREAD

**Issue by walec51** [resilience4j/resilience4j#755] opened 2019-11-18 19:44 UTC
I propose a method that can be manually called on a rate limiter to consume the remaining available permissions in the current cycle.

**Comment by RobWin** [comment] 2019-11-19 08:22
Hi,

just out of interest. What is the use case?

**Comment by walec51** [comment] 2019-11-19 09:17
I want to have the same RateLimiter config for my server API and main client of that API. After implementing https://github.com/resilience4j/resilience4j/issues/752 I can sync their clock and therefore their limit period. However there still might be a slight offset of limit periods on the client and server. To support this corner case when the server gives me an error indicating that I've done to much requests I can close the current period on my client to stop the bleeding.

**Comment by RobWin** [comment] 2019-11-19 09:19
ok, thanks

**Comment by RobWin** [comment] 2020-01-29 19:18
FYI @storozhukBM

**Comment by RobWin** [comment] 2020-10-29 12:22
Duplicate of https://github.com/resilience4j/resilience4j/issues/1228

**Closed by RobWin** 2020-10-29 12:22 UTC
Labels: enhancement
