### ISSUE TITLE
Split package issue using resilience4j , when using Java 11 modules

### ISSUE THREAD

**Issue by ekanthi** [resilience4j/resilience4j#963] opened 2020-04-21 21:50 UTC
Resilience4j version: 1.3.1

Java version: 11

Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules io.github.resilience4j.springboot2 and resilience4j.spring.boot.common export package io.github.resilience4j.ratelimiter.autoconfigure to module C...

The issue is both these jars have the same package name and Java 11 module system does not allow split packages.

**Comment by ekanthi** [comment] 2020-04-21 21:54
There are issues with not only ratelimiter.autoconfigure, but other autoconfigure packages like circuitbreaker.autoconfigure, bulkhead.autoconfigure , retry.autoconfigure, timelimiter.autoconfigure

**Comment by RobWin** [comment] 2020-04-22 06:41
Thanks.
It's a duplicate of https://github.com/resilience4j/resilience4j/issues/887.
Fixed in the next release 1.4.0

**Closed by RobWin** 2020-04-22 06:41 UTC
