### ISSUE TITLE
Resilience4j with spring webflux

### ISSUE THREAD

**Issue by srinivasa1225** [resilience4j/resilience4j#262] opened 2018-09-14 04:16 UTC
Hi,

There is some issue in implementing the resilience4j with spring webflux.using 0.13.1 version

Regards,
Srinivasa

**Comment by srinivasa1225** [comment] 2018-09-14 04:18
in case of server errors resilience 4j is not recognising as the server encountered the issue. it is taking it as success.os in failed cases also circuit-breaker is not opened.can you please let me know how to implement it for webflux

**Comment by storozhukBM** [comment] 2018-09-27 20:12
Hi @srinivasa1225,
We had one bug similar to your description, but it was reproducible only with successes #260
Maybe you can provide some test, code snippet or detailed steps that can help to reproduce this bug, because now it is not very clear.

**Comment by srinivasa1225** [comment] 2018-10-05 01:16
Thanks for your quick reply.The scenario is as below :

1. We are interacting with the downstream system using Spring webflux Webclient. 
2. The expectation is that resilience 4j opens the circuit breaker, if the down stream system is down or response time out(500 http code) .
3. But in actual,  it is not opening the circuit  breaker as expected.
4. When we analysed the code, observed that resilience 4j is not checking for the internal error 500, but returning success always.
5. However, when we use blocking mechanism, resilience 4j is working as excepted, which is against the webflux/reactive behaviour.

Hope this helps. Unfortunately, could not share the usage code, being proprietary. 
Requesting your suggestion/direction on the above issue.

**Comment by RobWin** [comment] 2018-10-08 10:16
Yes, our CircuitBreaker reacts only on exceptions. If you want that something triggers the CircuitBreaker, you must throw an exception. For example, a `WebApplicationException` should trigger the CircuitBreaker.

**Comment by ndhilliprasad** [comment] 2018-12-02 14:53
@srinivasa1225 if you are interested 

```java

CircuitBreaker circuitBreaker = CircuitBreaker.of("circuit", CircuitBreakerConfig.ofDefaults())

webClient.post()
                .uri("/test")
                .contentType(MediaType.APPLICATION_JSON)
                .syncBody(requestBody)
                .retrieve()
                .onStatus(HttpStatus::is5xxServerError, clientResponse -> Mono.error(new CustomException()))
                .bodyToMono(new ParameterizedTypeReference<Map<String, String>>() {})
                .transform(CircuitBreakerOperator.of(circuitBreaker))
                .onErrorResume(ex -> doFallback());
```

**Comment by RobWin** [comment] 2019-04-03 11:11
In 0.140 the CircuitBreakerConfig allows to configure an onResult predicate.
You can use this predicate to check the response and record failures whenever the HttpStatus is 500.

**Comment by RobWin** [comment] 2019-04-03 11:13
I close this in favour of https://github.com/resilience4j/resilience4j/issues/384

**Closed by RobWin** 2019-04-03 11:13 UTC
Labels: needs investigation, question
