### ISSUE TITLE
Bulkhead - not working as expected

### ISSUE THREAD

**Issue by scalablepuppets** [resilience4j/resilience4j#596] opened 2019-08-28 15:05 UTC
Yaml Config:

instances:
        defaultInstance:
            maxConcurrentCalls: 1
            maxWaitDuration: 1ms

Java Code:
Method annotated with : 
@Bulkhead(name = "defaultInstance",fallbackMethod="fallback_BH")

private String fallback_BH(BulkheadFullException e) {
		return "Bulkhead Full - fallback called";
} 

Q- I am expecting that rest of the concurrent calls will be directed to fallback method once the limit of 1 call is reached on a method, but that's not happening , the calls are blocked on the method annotated with @Bulkhead till it responds back.

Please suggest, if I need to change my implementation.

**Comment by RobWin** [comment] 2019-08-28 16:37
Is that the full yaml file? The prefix `resilience4j.bulkhead` is missing.

**Comment by RobWin** [comment] 2019-08-28 16:39
You are using a semaphore-based Bulkhead. Yes, it's normal that all threads are waiting until `maxWaitDuration` is elapsed before the exception is thrown.

**Comment by scalablepuppets** [comment] 2019-08-28 23:07
Thanks Rob, please find the yaml config as below which am using, I was hoping that the exception would be thrown but that's not happening.

resilience4j.bulkhead:
    configs:
        default:
            eventConsumerBufferSize: 10
            maxConcurrentCalls: 1
    instances:
        defaultInstance:
            maxConcurrentCalls: 1
            maxWaitDuration: 1ms

**Comment by RobWin** [comment] 2019-08-29 06:47
I can't reproduce it in our [Spring Boot 2 demo](https://github.com/resilience4j/resilience4j-spring-boot2-demo).

I added locally a Thread.sleep of 10s to the `BackendAConnector.success` method and configured the Bulkhead as follows:

```
resilience4j.bulkhead:
    instances:
        backendA:
            maxConcurrentCalls: 1
            maxWaitDuration: 1s
```

I invoked the endpoint `http://localhost:9080/backendA/success` twice. The second call fails with

```
{
  "timestamp": "2019-08-29T06:44:29.563+0000",
  "path": "/backendA/success",
  "status": 500,
  "error": "Internal Server Error",
  "message": "Bulkhead 'backendA' is full and does not permit further calls"
}
```

When I add a fallback -> `@Bulkhead(name = "backendA", fallbackMethod = "fallback")`
The second call returns:

`Recovered : io.github.resilience4j.bulkhead.BulkheadFullException: Bulkhead 'backendA' is full and does not permit further calls`


I can't reproduce it.

**Comment by scalablepuppets** [comment] 2019-08-29 12:47
really appreciate your time Rob ! I will test it shortly and update you.

**Comment by scalablepuppets** [comment] 2019-08-29 13:51
Thanks, am able to produce it, just thought to share my observation as I see some scope of improvement:
a. with @BulkHead annotation, I can not specify the fallback method name, if I specify I get 'java.lang.NoSuchMethodException:fallback(,class java.lang.Throwable)' . error.

b. I used Postman Collection runner to send couple of concurrent request, in this case all the request went into the blocking mode and eventually got completed after Thread.sleep time was over.

c. If I initiate the request sequentially one after another (there is some lag time in switching) I get the desired results.

**Comment by RobWin** [comment] 2019-08-29 13:54
Can you provide a GitHub repo where you reproduced it?

**Comment by RobWin** [comment] 2019-08-29 14:05
How do you run concurrent requests in the Postman Collection Runner?

**Comment by RobWin** [comment] 2019-08-29 14:10
Even wen I run multiple Collection Runners in parallel, it works for me:
![image](https://user-images.githubusercontent.com/5815046/63947589-7d15a400-ca77-11e9-8960-cfbd20fbaf26.png)

**Comment by scalablepuppets** [comment] 2019-08-30 14:28
Thanks Rob, I will test it tonight with another Rest Client.

**Comment by scalablepuppets** [comment] 2019-09-05 08:24
Wrote a custom Python Script and tested using the trusted SOAPUI and it works as expected.

**Comment by cgarman1** [comment] 2020-02-04 18:59
I'm actually seeing what I think is the same behavior with @Bulkhead(name = "BACKEND", fallbackMethod = "fallback", type = Bulkhead.Type.THREADPOOL) where the fallback is completely ignored. However if I switch the type to Bulkhead.Type.SEMAPHORE everything works as I expected it should by calling the fallback method.

**Comment by RobWin** [comment] 2020-02-04 19:00
Its fixed in the next version. Hopefully released tomorrow

**Comment by cgarman1** [comment] 2020-02-04 19:01
Ok great! I will test once it is released.

**Comment by RobWin** [comment] 2020-02-05 08:30
v.1.3.0 has been released. Maven Central Sync might take some time.

**Comment by cgarman1** [comment] 2020-02-05 14:20
Didn't notice this before but it looks like both 1.2.0 and 1.3.0 still use a couple of the 1.1.0 modules...which now produces a boot startup error with 1.3.0

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    io.github.resilience4j.circuitbreaker.configure.CircuitBreakerConfiguration.createCircuitBreakerRegistry(CircuitBreakerConfiguration.java:141)

The following method did not exist:

    io.github.resilience4j.circuitbreaker.CircuitBreakerRegistry.of(Ljava/util/Map;Lio/github/resilience4j/core/registry/RegistryEventConsumer;Lio/vavr/collection/Map;)Lio/github/resilience4j/circuitbreaker/CircuitBreakerRegistry;

**Comment by RobWin** [comment] 2020-02-05 14:22
The Spring Boot 2 demo works fine. Sure it's not an issue in your build script?

**Comment by cgarman1** [comment] 2020-02-05 14:30
I don't think so because the only import I have in my pom is resilience4j-spring-boot2...maven is bringing in everything else. Otherwise I have removed all application config except annotations...but I'm checking

```
    <dependency>
      <groupId>io.github.resilience4j</groupId>
      <artifactId>resilience4j-spring-boot2</artifactId>
      <version>1.3.0</version>
    </dependency>
```

**Comment by cgarman1** [comment] 2020-02-05 14:59
Once I added the following dependencies to override what is coming in by default it starts up fine...see below.

However, I'm still seeing the same behavior I commented on yesterday where the fallback method of @Bulkhead doesn't fire when type = Bulkhead.Type.THREADPOOL and a io.github.resilience4j.bulkhead.BulkheadFullException exception is instead thrown back to the client. I was expecting to be able to catch and handle this situation myself in the fallback method.

```
    <dependency>
      <groupId>io.github.resilience4j</groupId>
      <artifactId>resilience4j-circuitbreaker</artifactId>
      <version>1.3.0</version>
    </dependency>
    <dependency>
      <groupId>io.github.resilience4j</groupId>
      <artifactId>resilience4j-micrometer</artifactId>
      <version>1.3.0</version>
    </dependency>
    <dependency>
      <groupId>io.github.resilience4j</groupId>
      <artifactId>resilience4j-timelimiter</artifactId>
      <version>1.3.0</version>
    </dependency>
```

**Comment by RobWin** [comment] 2020-02-05 15:00
Can you show me how your code looks like?

**Comment by cgarman1** [comment] 2020-02-05 15:05
Ok I had to sanitize things a bit but this is what I'm doing

```
	@Bulkhead(name = "BACKEND", fallbackMethod = "fallback", type = Bulkhead.Type.THREADPOOL)
	@Override
	public CompletableFuture<ResponseTO> retrieveAccountDetails(AccountDetailsRequestTO request) {
		try {
			return CompletableFuture.completedFuture(client.getAccountDetails(request));
		} catch (RuntimeException e) {
			LOGGER.error(NestedExceptionUtils.getMostSpecificCause(e).getMessage());
			return retrieveErrorResponse();
		} 
	}
	
	@Override
	public CompletableFuture<ResponseTO> fallback(AccountDetailsRequestTO request, Exception e) {
		LOGGER.error(NestedExceptionUtils.getMostSpecificCause(e).getMessage());
		return retrieveErrorResponse();
	}
```

**Comment by RobWin** [comment] 2020-02-05 15:25
I investigate it tomorrow in more depth. I come back to you. Maybe it's an issue in the BulkheadAspect error handling. If you also use add a CircuitBreaker (like in the demo) and add your fallback method there, it should definitely work.

**Comment by cgarman1** [comment] 2020-02-05 15:26
Yes, it definitely works when I add the @CircuitBreaker

**Comment by dlsrb6342** [comment] 2020-02-06 01:48
> Didn't notice this before but it looks like both 1.2.0 and 1.3.0 still use a couple of the 1.1.0 modules...which now produces a boot startup error with 1.3.0
> 
> ```
> An attempt was made to call a method that does not exist. The attempt was made from the following location:
> io.github.resilience4j.circuitbreaker.configure.CircuitBreakerConfiguration.createCircuitBreakerRegistry(CircuitBreakerConfiguration.java:141)
> The following method did not exist:
> io.github.resilience4j.circuitbreaker.CircuitBreakerRegistry.of(Ljava/util/Map;Lio/github/resilience4j/core/registry/RegistryEventConsumer;Lio/vavr/collection/Map;)Lio/github/resilience4j/circuitbreaker/CircuitBreakerRegistry;
> ```

Hi @cgarman1 
Are you using `spring-cloud-depenecies` as a dependecyManagement?

**Comment by RobWin** [comment] 2020-02-06 09:16
The issue is here

```
 if (CompletionStage.class.isAssignableFrom(returnType)) {
            // threadPoolBulkhead.executeSupplier throws a BulkheadFullException, if the Bulkhead is full.
            // The BulkheadFullException is not  handled correctly by the FallbackDecorator.
            return threadPoolBulkhead.executeSupplier(() -> {
                try {
                    return ((CompletionStage<?>) proceedingJoinPoint.proceed())
                        .toCompletableFuture().get();
                } catch (ExecutionException e) {
                    throw new CompletionException(e.getCause());
                } catch (Throwable e) {
                    throw new CompletionException(e);
                }
            });
        }
```
In the case your method returns a `CompletableFuture` or `CompletionStage`:
The CircuitBreaker Aspect returns a failed future which is completed exceptionally with a `CallNotPermittedException` when the CircuitBreaker is open. Retry and RateLimiter behave similar.

The ThreadPoolBulkhead is different, because it does not return a CompletionStage when a task could not be submitted, because the Bulkhead is full. The ThreadPoolBulkhead throws a BulkheadFullException instead. Analog to the ThreadPoolExecutor which throws the RejectedExecutionException.

The BulkheadAspect can rethrow the BulkheadFullException or convert it to a failed future? What do you think a user expects? If no fallback method is configured, does a user expect a failed future or a RuntimeException when using the Bulkhead annotation?

**Comment by RobWin** [comment] 2020-02-06 13:17
Problem is fixed in 1.4.0-SNAPSHOT.
But I will release it as 1.3.1 as soon as possible

**Comment by cgarman1** [comment] 2020-02-06 14:10
> > Didn't notice this before but it looks like both 1.2.0 and 1.3.0 still use a couple of the 1.1.0 modules...which now produces a boot startup error with 1.3.0
> > ```
> > An attempt was made to call a method that does not exist. The attempt was made from the following location:
> > io.github.resilience4j.circuitbreaker.configure.CircuitBreakerConfiguration.createCircuitBreakerRegistry(CircuitBreakerConfiguration.java:141)
> > The following method did not exist:
> > io.github.resilience4j.circuitbreaker.CircuitBreakerRegistry.of(Ljava/util/Map;Lio/github/resilience4j/core/registry/RegistryEventConsumer;Lio/vavr/collection/Map;)Lio/github/resilience4j/circuitbreaker/CircuitBreakerRegistry;
> > ```
> 
> Hi @cgarman1
> Are you using `spring-cloud-dependencies` as a dependecyManagement?
> I got same issue with spring-cloud-dependencies because they use 1.1.0 version in spring-cloud-circuitbreaker-resilience4j. Following is my pom.xml.
> 
> ```
>   <dependencies>
>     <dependency>
>       <groupId>io.github.resilience4j</groupId>
>       <artifactId>resilience4j-spring-boot2</artifactId>
>       <version>1.3.0</version>
>     </dependency>
>   </dependencies>
> 
>   <dependencyManagement>
>     <dependencies>
>       <dependency>
>         <groupId>org.springframework.cloud</groupId>
>         <artifactId>spring-cloud-dependencies</artifactId>
>         <version>Hoxton.SR1</version>
>         <type>pom</type>
>         <scope>import</scope>
>       </dependency>
>     </dependencies>
>   </dependencyManagement>
> ```
> 
> But currently we cannot exclude specific dependencies from dependencyManagement. Please see https://issues.apache.org/jira/browse/MNG-5600.
> So I think we need to add our dependencies manually to override as you did.

Ah ok...yeah I missed that...yes that is exactly what I did/have

**Comment by cgarman1** [comment] 2020-02-06 14:22
> The issue is in the BulkheadAspect.
> 
> ```
>  if (CompletionStage.class.isAssignableFrom(returnType)) {
>             // threadPoolBulkhead.executeSupplier throws a BulkheadFullException, if the Bulkhead is full.
>             // The BulkheadFullException is not  handled correctly by the FallbackDecorator.
>             return threadPoolBulkhead.executeSupplier(() -> {
>                 try {
>                     return ((CompletionStage<?>) proceedingJoinPoint.proceed())
>                         .toCompletableFuture().get();
>                 } catch (ExecutionException e) {
>                     throw new CompletionException(e.getCause());
>                 } catch (Throwable e) {
>                     throw new CompletionException(e);
>                 }
>             });
>         }
> ```
> 
> In the case your method returns a `CompletableFuture` or `CompletionStage`:
> The CircuitBreaker Aspect returns a failed future which is completed exceptionally with a `CallNotPermittedException` when the CircuitBreaker is open. Retry and RateLimiter behave similar.
> 
> The ThreadPoolBulkhead is different, because it does not return a CompletionStage when a task could not be submitted, because the Bulkhead is full. The ThreadPoolBulkhead throws a BulkheadFullException instead. Analog to the ThreadPoolExecutor which throws the RejectedExecutionException.
> 
> `threadPoolBulkhead.executeSupplier` throws a BulkheadFullException, if the Bulkhead is full.
> The BulkheadFullException is not handled correctly by the FallbackDecorator.
> 
> The BulkheadAspect can rethrow the BulkheadFullException or convert it to a failed future? What do you think a user expects? If no fallback method is configured, does a user expect a failed future or a RuntimeException when using the Bulkhead annotation?
> 
> I prefer to return a failed future.

So if no fallback is configured, to me the existing behavior is fine. However if I have a fallback method configured, I expect it to be called (instead of throwing BulkheadFullException) and let me decide what to do. Basically my use case if that I'm retrofitting an existing aggregation service and want to add this functionality without impacting multiple layers of the application with additional try/catch logic. I'm wanting to provide some process isolation via separate thread pool (via @Bulkhead) and in the case that it is full, I want to be able to dummy out a response for my downstream service call and return what data I did get from the other service calls back to my client (that is what I am using the fallback method for...i'm creating my own future there). To me the annotation should not make any assumptions about what to return...it should just see that since there was a fallback method configured I will call that method and let the developer determine what gets returned from there.

**Comment by RobWin** [comment] 2020-02-06 14:59
The existing Bulkhead Aspect behavior has been adapted to match the behavior of the CircuitBreaker, Retry and RateLimiter Aspects. That means if on don't have a fallback method the CompletableFuture which is returned will be completed exceptionally with a BulkheadFullException.
If you have a fallback method, it will be invoked correctly now.

**Comment by RobWin** [comment] 2020-02-06 16:51
1.3.1 has been released. Maven Sync is running.

**Closed by RobWin** 2020-02-06 16:51 UTC
Labels: help wanted

**Comment by cgarman1** [comment] 2020-02-06 20:39
Yes, that works as I expected. However one question...I assume that configuring fallback on @Bulkhead that itself does not throw another error will cause @CircuitBreaker to never get called, correct?

**Comment by RobWin** [comment] 2020-02-06 20:50
Yes, the aspects decorate your method like an onion and have a preconfigured order.
Retry -> CircuitBreaker -> RateLimiter -> TineLimiter -> Bulkhead -> method.

Exceptions propagate from right to left. Ever decorator has the possibility to recover from an exception (fallback). In your case you should add the fallback method to the CircuitBreaker. At least if you don't use Retry, but only CircuitBreaker, TimeLimiter and ThreadPoolBulkhead.

**Comment by cgarman1** [comment] 2020-02-06 21:12
Yeah ok that's what I thought
