### ISSUE TITLE
Async Retry doesn't emit `RetryOnRetryEvent` on non-exceptional retried result

### ISSUE THREAD

**Issue by vnwhlr** [resilience4j/resilience4j#1275] opened 2020-12-17 00:02 UTC
### Resilience4j version:
1.6.1 

### Java version:
14.0.2_12 (Kotlin 1.3.72)

Ran into this while working on #1274 - I ended up with a solution that may or may not have looked a lot like [this](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-kotlin/src/main/kotlin/io/github/resilience4j/kotlin/retry/Retry.kt#L29). However, I found that when retrying a result that wasn't a thrown exception, the `EventConsumer` I attached to my `Retry` wouldn't get a `RetryOnRetryEvent`. I think that's because [`AsyncContextImpl` doesn't generate that event in `onResult`](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-retry/src/main/java/io/github/resilience4j/retry/internal/RetryImpl.java#L319-L330). Unfortunately, because the counters for the number of retries and last exception are private, there's no (direct) way to access them to generate the `RetryOnRetryEvent` yourself.

**Comment by RobWin** [comment] 2020-12-17 11:33
Hi, 

thank you.
Would you like to create a bugfix PR?

**Comment by piyushmor** [comment] 2021-05-25 18:15
it would be helpful if you can share which decorator/execute method you are using

**Comment by RobWin** [comment] 2022-12-12 14:25
Duplicate of https://github.com/resilience4j/resilience4j/issues/1761

**Closed by RobWin** 2022-12-12 14:25 UTC
Labels: bug
