### ISSUE TITLE
Could there be potential memory leak risk by using default ThreadPoolBulkhead ? 

### ISSUE THREAD

**Issue by QiyuZ** [resilience4j/resilience4j#918] opened 2020-03-14 04:54 UTC
Resilience4j version: 1.3.1

Java version: 8

Hi Amazing developers,

I saw a piece of code in FixedThreadPoolBulkhead for cleanup

```    private void cleanup() {
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            executorService.shutdown();
            try {
                if (!executorService.awaitTermination(5, TimeUnit.SECONDS)) {
                    executorService.shutdownNow();
                }
            } catch (InterruptedException e) {
                if (!executorService.isTerminated()) {
                    executorService.shutdownNow();
                }
                Thread.currentThread().interrupt();
            }
        }));
    }

```

It will shut down the executorService when JVM's down.  (Because of addShutdownHook)
But in my case, I have applications based on microservices that means I could do hot deploy an app for several times without restart the sever. In this case, the previous executorService  has not been shut down, right? What can I do to shut it down when I destroy the app?
Thanks

Best,
Qiyu

**Comment by Romeh** [comment] 2020-03-15 18:56
@QiyuZ  can you please share more about your micro-services stack , do u use spring cloud with kubernetes  for example ?

**Comment by QiyuZ** [comment] 2020-03-15 23:53
@Romeh Thanks for catching up. Our micro-service apps are in J2EE framework using Wildfly (Jboss) as application server. So instead of like docker container,  apps share same jvm in wildfly. We could redeploy the app. And usually we will not shut down sever, that means after redeployment the  executorService is still alive.

**Comment by RobWin** [comment] 2020-03-16 07:39
Hi,
I close this issue. because it's a somehow a duplicate of #913. 
We have to make the cleanup/close method public and also add a cleanup method to the registry. 
You can then add a framework-specific shutdown hook and invoke the cleanup/close method of the registry.

**Closed** 2020-03-16 07:39 UTC
