### ISSUE TITLE
Spring Boot health status switch to DOWN when circuit breaker is opened

### ISSUE THREAD

**Issue by jhaeyaert** [resilience4j/resilience4j#607] opened 2019-09-09 10:09 UTC
Hello,

I'm using circuit breaker in a reactive Spring Boot application and I noticed that there were an odd behavior with global health of my application when a circuit breaker is opened. 

By default, all circuit breakers contribute to the health indicator and when a circuit breaker goes opened, its corresponding health status switch to DOWN, so the global health status too. 

This behavior has a huge repercussion because when a remote service used by the application is in a bad shape, all instances of the application open the circuit breaker. As a consequence all health statuses switch to DOWN so all instances are kicked out of the load balancer and the application became totally unavailable.

We could consider this behavior makes sense but, sometimes, even a non critical functionality can lead to a service interruption. It appears that the circuit breaker supposed to prevent application from being unavailable just do the opposite declaring the whole application as DOWN.

Given that, does it make sense to have such a behavior by default ? Maybe we could consider that status health check must remain UP (or UNKNOWN) whatever the state of the circuit breaker (CLOSED, OPEN, ...) ? Another solution could be disabling auto configuration of health check by default and let the developer enable health check explicitly for each circuit breaker ?

**Comment by RobWin** [comment] 2019-09-09 10:15
Hi,

I agree. The CircuitBreaker health indicators were developed long before we added Dropwird Metrics, Prometheus and Micrometer support. I would actually like to remove the Health Indicators completely, but we can't, because we want to be backward-compatible.
But you can disable health indicators globally or per CircuitBreaker instance via the configuration.

For example:

```
resilience4j.circuitbreaker:
    configs:
        default:
            registerHealthIndicator: false
```

**Comment by jhaeyaert** [comment] 2019-09-09 11:28
Thanks for your response.

It seems that even when creating a default configuration it is still necessary to explicitly inherit from for each circuit breaker instance. That's good to me but I think it is not a safe solution at long term cause I think most of developers don't expect this behavior when they implement circuit breaker (I was expecting more resilience of my application and it appears that, by default, adding a circuit breaker increase the probability of unavailability of my application).

Maybe It could be interesting to change the default behavior (or remove health) in a future major version (v1) and provide a migration guide to explicitly detail breaking changes.

Thanks

**Comment by RobWin** [comment] 2019-09-09 12:29
Yes, but you only have to inherit from default, if you want to overwrite the default properties, otherwise not.

**Comment by KaiStapel** [comment] 2019-09-10 12:26
Hi. I agree with @jhaeyaert. Not changing health status on open circuits should be the default. This is about increasing resilience, not decreasing it.

**Comment by RobWin** [comment] 2019-09-10 14:42
Fine for me.
Someone interested in creating a PR?
You just have to adapt [RateLimitersHealthIndicator](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring-boot-common/src/main/java/io/github/resilience4j/ratelimiter/monitoring/health/RateLimitersHealthIndicator.java#L56) and [CircuitBreakersHealthIndicator](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring-boot-common/src/main/java/io/github/resilience4j/circuitbreaker/monitoring/health/CircuitBreakersHealthIndicator.java#L69) and the tests.

**Comment by jhaeyaert** [comment] 2019-09-11 07:37
I can handle the development if you want.

For that I need to know your position regarding the following approaches:
- Disable health indicator by default. The health indicators are no longer registered by default.
- Set the status to UP or UNKNOWN (but keep state in detail) when circuit breaker is opened (same for rate limiter). The idea behind is to make sure that status does not have impact on the global health status.

Maybe we could mix the both ?

**Comment by RobWin** [comment] 2019-09-11 07:59
1.) Yes, disable health indicator by default.
2.) I think we should keep it as it is, because of backward-compatibility. The remote system is actually down. The health status of a RabbitMQ or DB health indicator is also down, when the RabbitMQ/ DB is not reachable.

Users should better use the metrics endpoint to retrieve the state of the circuitbreakers.

**Comment by erwinc1** [comment] 2019-09-11 12:32
Actually, this is a problem that we solved several days ago as well by looking into this healthIndicator class (luckily).

This above problem fully explains why the app goes down once the circuit goes to OPEN right. But what about the general performance? I've experienced a huge drop in performance with the health indicator enabled in general without any failing backends (so circuit always CLOSED). What's the deal with that?

For example; I was able to hit at least factor 50 more load with the health indicator off!

**Comment by KaiStapel** [comment] 2019-09-11 12:38
Maybe the performance impact is worth its own dedicated ticket?

**Comment by RobWin** [comment] 2019-09-11 12:43
Strange, I can't see how this is related to each other.

**Comment by erwinc1** [comment] 2019-09-11 13:38
> Strange, I can't see how this is related to each other.
> Which Resilience4j version to you use?

0.17.0

**Comment by RobWin** [comment] 2019-09-11 13:42
Could you please create a new issue and tell us which tools you used to measure the performance?

**Comment by RobWin** [comment] 2019-09-12 07:34
@jhaeyaert I would like to include this into v1.0.0.
Do you think you have time to contribute a PR?

**Comment by RobWin** [comment] 2019-09-13 07:51
I quickly created a PR https://github.com/resilience4j/resilience4j/pull/615

**Comment by marcust** [comment] 2019-09-23 11:53
@RobWin I am under the impression that this is combination with #571 did not really achieve what it was supposed to do. 
In 0.17.0 I could disable any change to the `/health` endpoint by disabling the options indicated above. Now with 1.0.0 I still get `"circuitBreakers":{"status":"UNKNOWN"},"rateLimiters":{"status":"UNKNOWN"}` in my `/health` endpoint, even if it does not try to register any health indicator. There seems to be no way to get Resilience4j out of the health indicator part of the system anymore?

(I actually have a test on the output of `/health` because I had a similar issue as the reporter, and I don't want Resilience4j in my health endpoints at all)

**Comment by RobWin** [comment] 2019-09-23 12:01
Yes, seems to be a bug introduced by the change of the HealthIndicator.

**Comment by dlsrb6342** [comment] 2019-09-23 14:32
Yes.. Because of changes, HealthIndicator always exists whether instances not registered or not. I think we should add property that can disable HealthIndicator

**Comment by RobWin** [comment] 2019-09-25 08:37
I reopened the issue.
Who would like to contribute a fix for this?

**Comment by RobWin** [comment] 2019-09-27 08:03
I created a PR

**Comment by hjacobs** [comment] 2019-10-24 13:24
We ran into this problem today and will use the config property to disable the health indicator: https://twitter.com/try_except_/status/1187358754410512386

**Comment by dlsrb6342** [comment] 2019-10-24 13:33
@hjacobs 
From v1.1.0, health indicator is disabled by default. Which version do you use?

**Comment by worldtiki** [comment] 2019-10-26 17:26
Any chance we can revisit this issue?

Looking at other implementations (Hystrix), the circuit breaker status details are displayed in the health endpoints but they do not affect the overall status.
I think this is a good compromise: it does not cause the application to be killed by failing healthchecks but it still exposes the correct health status instead of hiding it.

I believe this behaviour is a sensible default (which users should still be able to override if they wanted).
I also think that not having this difference between Hystrix and Resilience would simplify developers who are migrating to resilience4j and want/expect the identical behaviours.

I'm happy to open a draft with these changes if there is interest.

**Comment by RobWin** [comment] 2019-10-26 17:35
Would you like to propose a PR?

**Comment by worldtiki** [comment] 2019-10-26 18:59
I'll create a draft.

In the meantime I also opened this ticket https://github.com/spring-projects/spring-boot/issues/18753 to gather some more feedback.
This change will allow us to have a consistent behaviour between Resilience4j and Hystrix (and others), but not across **all** Spring Boot Health Indicators. I don't know if that's possible or even something that the Spring folks want to do but I'm interested to see if they have suggestions.

**Comment by sina-golesorkhi** [comment] 2019-10-29 11:03
@RobWin I do agree with @worldtiki but it would be also great if the `CallNotPermittedException` becomes stateful in the sense that it has the original problem as the root messages or the original exception as the root exception otherwise is it hard to debug why the CB was open.

**Comment by worldtiki** [comment] 2019-10-31 20:32
I raised #722 

@sina-golesorkhi that assumes there is a single root cause, but when a circuit breaker opens it's because of a cumulative of errors (potentially different).

**Comment by sina-golesorkhi** [comment] 2019-10-31 20:44
@worldtiki yes it is possible that multiple root causes exist but most of the times it happens because of one reason. Even if the circuit breaker opens because of multiple reasons the last one that caused it to open can be potentially used as the root cause wrapped in `CallNotPermittedException ` because at least it gives one of the multiple root causes compared to none of them. I think this way it helps to debug the the root cause easier/faster or on the health endpoint it can report with a count on different types of exceptions.

**Closed** 2019-11-17 09:13 UTC
Labels: enhancement

**Comment by sonia1004** [comment] 2021-08-02 16:09
I am using Circuit Breaker and getting all the health details when the service is down or up. When the circuit is open, the overall application status is UP which is fine as per my use case. But when I reading other posts I found out that other people talking about the issue when circuit is open their app status also shows down but I am not seeing that. HAs something changes that I am not aware of. I want to make sure if I am not missing anything. 
Please help.

{
  "status": "UP",
  "components": {
    "circuitBreakers": {
      "status": "UNKNOWN",
      "details": {
        "customer": {
          "status": "CIRCUIT_OPEN",
          "details": {
            "failureRate": "33.333332%",
            "failureRateThreshold": "30.0%",
            "slowCallRate": "0.0%",
            "slowCallRateThreshold": "100.0%",
            "bufferedCalls": 6,
            "slowCalls": 0,
            "slowFailedCalls": 0,
            "failedCalls": 2,
            "notPermittedCalls": 1,
            "state": "OPEN"
          }
        }
      }
    },
    "ping": {
      "status": "UP"
    }
  }
}

**Comment by sonia1004** [comment] 2021-08-03 03:25
How to get the state of the circuit breaker(open or closed) from actuator health endpoint
