### ISSUE TITLE
CircuitBreaker: How to treat exceptions as a success

### ISSUE THREAD

**Issue by harishmbm** [resilience4j/resilience4j#568] opened 2019-08-15 11:30 UTC
Hi,

I have the following setup:

1. A 3rd party service (runs on localhost:8090/sample) and it always returns bad request (400).
```
@RestController
@RequestMapping
public class SampleController {
    @GetMapping("/sample")
    public ResponseEntity helloWorld(HttpServletResponse response) {
        System.out.println("Request received");
        return ResponseEntity.badRequest().body("{\"message\":\"this is a bad request\"}");
    }
}
```
2. In my main application where I am using circuit breaker, I am using RestTemplate to communicate it with the 3rd party service. I have ignored `org.springframework.web.client.HttpClientErrorException` from the circuit breaker.
3. The circuit breaker annotation is kept at method level like below:
```
    @CircuitBreaker(name = "callOtherService", fallbackMethod = "errorExternal")
    public String callOtherService() {
        System.out.println("Call received");
        return restTemplate.getForObject(URI.create("http://localhost:8090/sample"), String.class);
    }

public String errorExternal(Throwable throwable) {
        return "This is error from fallback triggered by external error";
    }
```
4. I am using following configuration (see `callOtherService` section)
```
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 4
      ringBufferSizeInHalfOpenState: 2
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 20s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      ignoreExceptions:
       - com.resilience4j.exception.BusinessException
       - feign.FeignException
      recordExceptions:
        - java.net.SocketTimeoutException
        - java.net.ConnectException
    shared:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 4
      ringBufferSizeInHalfOpenState: 2
      waitDurationInOpenState: 20s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      ignoreExceptions:
        - com.resilience4j.exception.BusinessException
  instances:
    callOtherService:
      baseConfig: default
      ringBufferSizeInClosedState: 4
      registerHealthIndicator: true
      ignoreExceptions:
        # We need to ignore 4xx errors returned by the server as they are valid business case.
        - org.springframework.web.client.HttpClientErrorException
      recordExceptions:
        # We need to record all http errors
        - org.springframework.web.client.RestClientException
```

Steps to reproduce:
1. Call the exposed endpoint 5-6 times. Verify the 3rd party service gets the call every time.
2. Shut down the 3rd party service.
3. Call the exposed endpoint again for 4 times. Check /actuator/health endpoint and you'll see that the circuit is OPEN now.
4. Wait for 20 sec.
5. Now health endpoint says circuit is HALF_OPEN.
6. Call exposed endpoint again for 2 times.
7. Check health endpoint and verify circuit is OPEN again.
8. Turn ON the 3rd party service.
9. Verify from health endpoint if circuit is HALF_OPEN.
9. Call the exposed endpoint. The call gets successful to 3rd party 2 times (size of ring buffer in half open state).
10. Health endpoint still HALF_OPEN.
11. All the calls to exposed endpoint are short-circuited and no call is attempted to the 3rd party.
12. The circuit breaker is never CLOSED again. And there is no way to recover from this situation apart from restart the server using the circuit breaker.

**Comment by RobWin** [comment] 2019-08-15 11:46
An ignored exceptions is NOT recorded as a successful call, it's totally ignored by the circuitbreaker.
The endpoint must return a 200 so that the call is recorded as a successful call.

**Comment by harishmbm** [comment] 2019-08-15 11:51
But it is not necessary for an endpoint to return 200 to show that it is running properly. If any endpoint is returning 400 (valid case if the request fails validation error) that means also that the endpoint is working, right?

**Comment by RobWin** [comment] 2019-08-15 11:58
Resilience4j is protocol and framework agnostic. That means it doesn't know anything about the protocol or framework you use. Exceptions are either treated as failures or ignored. There is no option yet to treat an exception as a success. It's an interesting use case and could be added to Resilience4j.
But for now the user of Resilience4j must handle the exception and convert it into a `ResponseEntity` instead of throwing an exception.

**Comment by RobWin** [comment] 2019-08-15 12:06
But I like the idea to add something like
```
recordsExceptionsAsSuccess:
       - org.springframework.web.client.HttpClientErrorException
```

**Comment by RobWin** [comment] 2019-08-15 12:13
In your case you can change your code to

```
public ResponseEntity callOtherService() {
        return restTemplate.getForEntity(URI.create("http://localhost:8090/sample"), String.class);
    }
```

And adapt the restTemplate error handler -> https://www.baeldung.com/spring-rest-template-error-handling

```
@Component
public class RestTemplateResponseErrorHandler implements ResponseErrorHandler {

    @Override
    public boolean hasError(ClientHttpResponse httpResponse)
      throws IOException {

        return httpResponse.getStatusCode().series() == SERVER_ERROR;
    }

    @Override
    public void handleError(ClientHttpResponse httpResponse)
      throws IOException {
        String statusText = response.getStatusText();
        HttpHeaders headers = response.getHeaders();
        byte[] body = getResponseBody(response);
        Charset charset = getCharset(response);
        switch (statusCode.series()) {
            case SERVER_ERROR:
                throw HttpServerErrorException.create(statusCode, statusText, headers, body, charset);
            default:
                throw new UnknownHttpStatusCodeException(statusCode.value(), statusText, headers, body, charset);
        }
    }
}hrows IOException {
 String statusText = response.getStatusText();
		HttpHeaders headers = response.getHeaders();
		byte[] body = getResponseBody(response);
		Charset charset = getCharset(response);
		switch (statusCode.series()) {
			case CLIENT_ERROR:
				throw HttpClientErrorException.create(statusCode, statusText, headers, body, charset);
			case SERVER_ERROR:
				throw HttpServerErrorException.create(statusCode, statusText, headers, body, charset);
			default:
				throw new UnknownHttpStatusCodeException(statusCode.value(), statusText, headers, body, charset);
		}
        }
    }
}
```

**Comment by harishmbm** [comment] 2019-08-15 12:17
Ok thanks for the code, I'll test it.

But there is definitely one bug i.e in HALF_OPEN state if 50% of calls fails (as defined by property failureRateThreshold), provided if they all are 4xx, then the circuit never closes back even if the 3rd party service is up and running and the only option to make our main endpoint work again is to restart the server.

**Comment by RobWin** [comment] 2019-08-15 12:24
I think you didn't get my answer or you didn't read it.

Ignored exceptions are totally ignroed. Let's say you have a Client which calls a remote service, but the client also validates the input and throws an exception. The validation exception should be ignored by the CircuitBreaker. That's when you should add an exception to the list of ignored exceptions.

But if the remote service returns a response and your client makes an exception out of it... .. That's up to the designer of the client. It's not something a protocol agnostic library can handle.
We could only add a new feature to Resilience4j and add a new list property for exceptions which should be treated as a success.

**Comment by harishmbm** [comment] 2019-08-15 12:37
Hi @RobWin,

`Ignored exceptions are totally ignored by the CircuitBreaker. They are neither counted as success nor failure.` I totally agreed here. What I wanted to say is if the circuit is in HALF_OPEN state and the remote service gives those errors which are ignored then the state of CircuitBreaker should not change. Now if 50% of such `ignored` exceptions have been thrown and after that if a valid call is made from the end user (postman) then too CircuitBreaker does not attempts calls to the remote client which makes the end user in blocked state.

I have made such sample [here](https://github.com/harishmbm/resilience4j-springboot/commits/master) where you can use `/callOtherService` endpoint to simulate this behaviour. You need to write a remote service which is as following:
```
@RestController
@RequestMapping
public class SampleController {
    @GetMapping("/sample")
    public ResponseEntity helloWorld(@RequestParam(required = false) String success) {
        System.out.println("Request received");
        if (Objects.nonNull(success)) {
            return ResponseEntity.ok().body("{\"message\":\"this is a good request\"}");
        }
        return ResponseEntity.badRequest().body("{\"message\":\"this is a bad request\"}");
    }
}
```

**Comment by RobWin** [comment] 2019-08-15 12:45
Which version are you using?
I think you are talking about a bug that was fixed in `0.17.0` -> https://github.com/resilience4j/resilience4j/issues/544

**Comment by harishmbm** [comment] 2019-08-15 12:49
Yes it looks same and I am using the following versions:

```
	<dependency>
		<groupId>io.github.resilience4j</groupId>
		<artifactId>resilience4j-spring-boot2</artifactId>
		<version>0.17.0</version>
	</dependency>

        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-feign</artifactId>
            <version>0.16.0</version>
        </dependency>
```

**Comment by RobWin** [comment] 2019-08-15 12:50
Let me check. There is a unit test which verifies the functionality.

**Comment by RobWin** [comment] 2019-08-15 13:01
This sentence is not clear to me 
> Now if 50% of such ignored exceptions have been thrown and after that if a valid call is made from the end user (postman) then too CircuitBreaker does not attempts calls to the remote client which makes the end user in blocked state.

I added another unit tests where the CircuitBreaker is in HALF_OPEN state. 
Then I throw 4 times an ignored exception and the CircuitBreaker still allows further 4 calls. Nothing is blocked. When I execute 4 successful calls, the CircuitBreaker transitions back to CLOSED.

**Comment by RobWin** [comment] 2019-08-15 13:06
Your method `callOtherService` has a fallback method specified.
`@CircuitBreaker(name = "callOtherService", fallbackMethod = "errorExternal")`

https://github.com/harishmbm/resilience4j-springboot/blob/master/src/main/java/com/resilience4j/service/Resilience4jService.java

**Comment by harishmbm** [comment] 2019-08-15 13:12
By that statement I meant that in HALF_OPEN state if the remote service still gives an error which is `ignored` then the circuit breaker behaves as OPEN (health endpoint still says HALF_OPEN) and does not makes any calls to remote service. I said 50% because in my case this situation is happening after 2 calls because I had set `ringBufferSizeInHalfOpenState: 2`

**Comment by harishmbm** [comment] 2019-08-15 13:16
Yes it have a fallback. Will it make any difference in HALF_OPEN state?

**Comment by RobWin** [comment] 2019-08-15 13:29
No, I was confused for a moment. The fallback does not change anything in HALF_OPEN state.

I'm not able reproduce it with https://github.com/resilience4j/resilience4j-spring-boot2-demo

I invoked `http://localhost:9080/backendA/failure` 5 times and waited until the state is HALF_OPEN.
Then I invoked `http://localhost:9080/backendA/ignore` 5 times and checked `http://localhost:9080/actuator/health`. No calls were buffered and all exceptions were ignored.
Then I called `http://localhost:9080/backendA/failure` 1 time and `http://localhost:9080/backendA/success` 2 times. The state changed as expected to CLOSED.

**Comment by RobWin** [comment] 2019-08-15 13:32
Could you update `resilience4j-feign` to `0.17.` 
The old version `0.16.0` might pull in the old version as a transitive dependency.

**Comment by harishmbm** [comment] 2019-08-15 13:36
Ok sure I will update the library version and post the test result here tonight.

**Comment by harishmbm** [comment] 2019-08-15 16:54
@RobWin Yes, I just verified that this issue is fixed in resilience4j-feign:0.17.0. Thanks for help.

**Comment by RobWin** [comment] 2019-08-15 16:55
No problem. Still I think we will add a new property to add exceptions which should be treated as a success.

**Comment by harishmbm** [comment] 2019-08-15 17:10
Yes that would be helpful.

**Comment by harishmbm** [comment] 2019-08-17 14:43
@RobWin thanks for the fix. Can you please tell me when are you going to release a new version of all libraries? I would really like to see at least https://github.com/resilience4j/resilience4j/pull/579 and https://github.com/resilience4j/resilience4j/pull/576 in the latest release.

**Closed** 2019-08-29 07:31 UTC
Labels: enhancement, implemented

**Comment by haotenks** [comment] 2020-03-09 16:56
Hi @RobWin ,

Actually I am facing an issue regarding this topic.
I am using: resilience4j-spring-boot2 <1.3.0>

Inside my yml file the following properties are set:

```
resilience4j.circuitbreaker:
  configs:
    default:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 4
        ringBufferSizeInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 20s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        ignoreExceptions:
          - com.ast.microservice.common.exception.ApplicationException
```

I have a service layer where the @CircuitBreaker is defined and contains a fallback method. 
That service is calling to Dao to retrieve data, if the data list is empty a ResourceNotFoundException is thrown (ResourceNotFoundException extends from ApplicationException which is defined under ignoreExceptions in yml) but the circuit becomes to OPEN and the code inside fallback method is executed instead of show the ResourceNotFoundException message.

Below is the service where the data is generated and the exception is thrown.
```
@Override
@CircuitBreaker(name = "findUsersDetails", fallbackMethod = "fallbackForFindUsersDetails")
public ResponseDto findUsersDetails(String fields, PageRequest pageRequest, SearchApiData searchInput)
            throws IOException {
        UserDao userDao = getUserDao();
        CustomPage<UsersDetailsViewModel> usersPage =
                userDao.getUsers(pageRequest, searchInput);
        List<UsersDetailsViewModel> usersList = usersPage.getContent();
        if (usersList.isEmpty())
            throw new ResourceNotFoundException("No data found");
        
        return usersResponseHandler.handleUsersApiResponse(usersList, fields);
    }
```
Do I am donig something wrong? or may be I missundertand ignoreExceptions functioanlity?

**Comment by RobWin** [comment] 2020-03-09 17:14
Sey the question is not clear to me. What do you want to achieve? Run the fallback only when the CircuitBreaker is open?

**Comment by haotenks** [comment] 2020-03-09 17:27
No, what I want is to see the ResourceNotFoundException which is inside the If statement. 
If ApplicationException is present in the IgnoreExceptions list and, ResourceNotFoundException extends from it, then, that should be the response, not the code inside fallback method.

This is the flow with expected result
1- Request to findUsersDetails
2- usersList is empty
3- if usersList is empty then throw ResourceNotFoundException
**4- See in the response that exception**

This is the current result:
1- Request to findUsersDetails
2- usersList is empty
3- if usersList is empty then throw ResourceNotFoundException
**4- The code inside fallback method is being called** 

The think is, why the fallback method is invoked if the  ResourceNotFoundException is present in the IgnoreExceptions list

**Comment by RobWin** [comment] 2020-03-09 17:33
The fallback mechanism doesn't take the CircuitBreakerConfig into account. It catches the exceptions which are part of the signature of your fallback method. You could narrow down the scope to more specific exceptions in your fallback method so that it does not catch ResourceNotFoundExceptions anymore. Or rethrow a ResourceNotFoundException in your fallback method.

**Comment by haotenks** [comment] 2020-03-09 17:56
Thank a lot for your help!
That way worked perfectly, the problem was solved

**Comment by aashishbimal** [comment] 2020-05-12 18:14
Hi Robwin,
How we will resolve the same problem address by haotenks using spring cloud circuit breaker as fallback always receive throwable object how to narrow down exception in that case.

**Comment by SidekickJohn** [comment] 2021-11-18 06:58
> The fallback mechanism doesn't take the CircuitBreakerConfig into account. It catches the exceptions which are part of the signature of your fallback method. Currently it's like a try/catch. If your fallback uses Throwable/Exception it catches everything. You could narrow down the scope to more specific exceptions in your fallback method so that it does not catch ResourceNotFoundExceptions anymore. Or rethrow a ResourceNotFoundException in your fallback method. You can have multiple fallback methods with the same name, but with different signatures (exceptions). Comparable to different catch blocks.

Hi @RobWin i came across the same "issue" as the other user (ghost). This comment really helped me understand what my problem was --> thanks a lot for this. 

Two things are vital in my opinion and I might have missed them in the documentation: 
- Fallback-Method is like a try-catch and is **always called**, even if CircuitBreaker is CLOSED --> I thought/expected it was only called if OPEN/HALF-OPEN. Meaning: "If the circuit-breaker aspect prevents calls from entering the encapsulated method the fallback-method will be called (States: OPEN/HALF-OPEN) ". 
- And as a follow-up using Throwable in the fallback signature makes every failed call run into this fallback-method --> Considering the CircuitBreaker as a try-catch I understand this now

--> Sorry to ask you that, but is the part about the fallback being always triggered mentioned in the CircuitBreaker documentation in this distinctness? Until now I was not aware of this (in my opinion) vital information.

**Comment by RobWin** [comment] 2021-11-18 10:50
It really depends on the signature of your fallback methods. If you catch `Exception`, the fallback method is called on every execption, not only when the CircuitBreaker is OPEN.

Usually it only makes sense to catch ony `CallNotPermittedException` in your fallback-method of your CircuitBreaker. But we wanted to be as flexible as possible.

**Comment by SidekickJohn** [comment] 2021-11-18 12:15
Thanks for clarifying and explaining!

**Comment by PetreVane** [comment] 2022-01-12 16:58
Same here. Thanks for suggesting how to handle exceptions & circuit breaker
