### ISSUE TITLE
Why TimeLimiter core module is not part of spring-boot-2 dependency?

### ISSUE THREAD

**Issue by gdinant** [resilience4j/resilience4j#697] opened 2019-10-17 10:00 UTC
Hi,

I was wondering why `resilience4j-timelimiter` wasn't a direct dependency of `resilience4j-spring-boot2` since it is a core module. We have access to circuitbreaker, retry, bulkhead or ratelimiter but not to this one.

Moreover, why would you put in place a circuitbreaker without wanting to handle timeouts? You will eventually end up queuing calls.

Thanks in advance for the explanation :).

**Comment by RobWin** [comment] 2019-10-17 11:45
Hi,

the CircuitBreaker does not queue any calls. The ThreadPoolBulkhead can queue calls.

This issue is a duplicate of https://github.com/resilience4j/resilience4j/issues/430
Please have a look at the discussion there.

**Closed** 2019-10-17 11:45 UTC
