### ISSUE TITLE
CircuitBreaker.decorateCompletionStage throws exception if circuit open

### ISSUE THREAD

**Issue by gedl** [resilience4j/resilience4j#269] opened 2018-09-29 17:27 UTC
calling `CircuitBreaker.decorateCompletionStage` is throwing an exception if the CB is open. 

Exhibit A:
```
	Supplier<CompletionStage<MyObject>> primaryResult = CircuitBreaker.decorateCompletionStage(
				this.circuitBreaker,
				main();

		Try<CompletionStage<MyObject>> recover = Try.ofSupplier(primaryResult)
				.recover(throwable -> {
					LOGGER.warn("Could not execute main. Recovering.", throwable);
					return recover();
				});
```

Exhibit B:
```
	Supplier<CompletionStage<MyObject>> primaryResult = CircuitBreaker.decorateSupplier(
				this.circuitBreaker,
				main();

		Try<CompletionStage<MyObject>> recover = Try.ofSupplier(primaryResult)
				.recover(throwable -> {
					LOGGER.warn("Could not execute main. Recovering.", throwable);
					return recover();
				});
```

if main() is defined as follows:
```
public void main() { throws RuntimeException();}
```

Calling any of the versions 100 times will open the circuit. However, the 101st execution of Exhibit A will bubble up a `CircuitBreakerOpenException` while exhibit B will call `recover()`

I would expect both to behave the same way.

Am I missing something?

**Comment by storozhukBM** [comment] 2018-09-29 19:03
By design `CircuitBreaker.decorateCompletionStage` and `CircuitBreaker.decorateSupplier` behave a differently.  
`CircuitBreaker.decorateSupplier` directly throws `CircuitBreakerOpenException`.
`CircuitBreaker.decorateCompletionStage` uses `CompletableFuture.completeExceptionally` to propagate exceptional state. 
That is why you should use `CircuitBreaker.decorateCompletionStage` with futures if you want them to work properly.
So it seems that everything works as expected. If not please describe your thoughts on it.

**Comment by storozhukBM** [comment] 2018-10-03 20:01
Not closing it for now. I'll add required documentation update.

**Comment by RobWin** [comment] 2019-04-03 11:22
I fix the bug in commit https://github.com/resilience4j/resilience4j/commit/6cc12382ce457b19270ce59af9506de304ac6bec

**Closed** 2019-04-03 11:25 UTC
Labels: documentation update, question
